name: lms
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.8.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.3
    # handle SVGs for Android, iOS, and Web.
  flutter_svg: ^0.22.0
  table_calendar: ^3.0.0
  flutter_calendar_carousel: ^2.0.2
  modal_progress_hud: ^0.1.3
  google_fonts: ^2.1.0
  flutter_icons: ^1.1.0
  file_picker: ^4.0.0
  uuid: ^3.0.4
  image_picker: ^0.8.3+3
  flutter_speed_dial: ^4.3.0
  random_string: ^2.0.1
  syncfusion_flutter_datagrid: ^19.3.48


  shared_preferences: ^2.0.6
  provider: ^5.0.0
  multi_image_picker2: ^5.0.2
  transparent_image: ^2.0.0
  flutter_form_builder: ^6.0.1
  rflutter_alert: ^2.0.2

  #for online vidoe tutorial
  jitsi_meet: ^4.0.0
  intl: ^0.17.0
  like_button: ^2.0.3
  readmore: ^2.1.0

  #firebase dependencies
  google_sign_in: ^5.0.5
  cloud_firestore: ^2.4.0
  firebase_storage: ^10.0.2
  firebase_messaging: ^10.0.5
  firebase_auth: ^3.0.1
  firebase_core: ^1.4.0
  http: ^0.13.3

  package_info_plus: ^1.0.6
  device_info_plus: ^2.1.0
  # which supports multiple columns with rows of varying sizes
  flutter_staggered_grid_view: ^0.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter


# The following section is specific to Flutter.
flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/Icons/
    - assets/images/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  
